[project]
name = "project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "catkin-pkg>=1.0.0",
    "empy>=4.2",
    "pycomm3>=1.2.14",
    "pydantic>=2.11.1",
    "pymodbus==3.8.6",
]
