<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>robotics_line</name>
  <version>0.0.0</version>
  <description>TODO: Package description</description>
  <maintainer email="nathanhampton40000@gmail.com">nathan</maintainer>
  <license>Apache-2.0</license>

  <depend>action_msgs</depend>
  <depend>actions_servers</depend>
  <depend>msg_publishers</depend>
  <depend>srv_services</depend>
  <depend>fanuc_interfaces</depend>
  <depend>camera_driver</depend>
  <depend>rclpy</depend>


  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
