# -*- coding: utf-8 -*-
"""DiceDetectionYolo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KNtVIBNoExaGwpEwSqFxMVw2esByXHb6
"""
# Check that the package has been installed
import os

import cv2
import torch
import ultralytics
from PIL import Image
from ultralytics import YOLO

print(ultralytics.__version__)

training_data_dir = "/content/datset"
data_zip = "dice_data_v2.zip"



cuda_available = torch.cuda.is_available()

if cuda_available:

  print("CUDA is available")
  # !nvidia-smi

else:

  message = """
    WARNING: In order to train the model, it is advisable to use GPU.
    Change runtime type to GPU from:
      menu Runtime -> Change runtime type -> Hardware accelerator -> GPU.
      And run all the cells again.
  """
  print(message)

def serialized_model_file(
    checkpoint="best",
    project=None,
    name=None
):
  """
    Returns the serialized file path.
  """
  return f"{project}/{name}/weights/{checkpoint}.pt"



def train(
    data,
    fallback="yolov12m.pt",
    epochs=100,
    augment=True,
    patience=25, # Number of epochs to wait without much improvement before stopping
    project=None,
    name=None,
    model_file=None,
    additional_args=dict()
):
  if project is None:
    project = "runs"
  if name is None:
    name = "train"
  cuda_available = torch.cuda.is_available()
  if not cuda_available:
    print("CUDA is not available, skipping train.")
    return

  if model_file is None:
    model_file = serialized_model_file("best", project, name)

  if os.path.exists(model_file):
    resume_training = True
    use_model = model_file
    print(f"Resuming training from {model_file}")
  else:
    resume_training = False
    use_model=fallback
    print(f"Starting training from {use_model}")

  model = YOLO(
      use_model,
  )

  model.train(
      data=data,
      resume=resume_training,
      epochs=epochs,
      optimizer="AdamW",
      lr0=0.0001,
      batch=16,
      augment=augment,
      name=name,
      project=project,
      patience=patience,
      imgsz=640,
      scale=0.5,  # S:0.9; M:0.9; L:0.9; X:0.9
      mosaic=1.0,
      mixup=0.0,  # S:0.05; M:0.15; L:0.15; X:0.2
      copy_paste=0.1,  # S:0.15; M:0.4; L:0.5; X:0.6
      **additional_args

  )

  # Evaluate model performance on the validation set
  return model.val()


project = "dice_detection"
name = "robo_data_train_3_yolo12m"
train_data_config = training_data_dir + "/data.yaml"
out_dir = project + "/" + name
# model_file = "/content/drive/MyDrive/robotics_line/dice_detection/half_data/weights/best.pt"
additional_args = {
    # "multi_scale": True,
    # "dropout":    0.1,
    # "hsv_v":      0.6, # Modifies the value (brightness) of the image by a fraction, helping the model to perform well under various lighting conditions.
    # "hsv_h":      0.05, # Adjusts the hue of the image by a fraction of the color wheel, introducing color variability. Helps the model generalize across different lighting conditions.
    # "hsv_s":      0.7, # Alters the saturation of the image by a fraction, affecting the intensity of colors. Useful for simulating different environmental conditions
}

# !export PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True
results = train(data=train_data_config, epochs=300, project=project, patience=10, name=name, additional_args = additional_args)


# !yolo val model=/content/drive/MyDrive/robotics_line/dice_detection/robo_data_train_2/weights/best.pt data=/content/datset/data.yaml split=test


Image.open("runs/detect/val3/val_batch0_pred.jpg")

Image.open(out_dir +"/results.png")

Image.open(out_dir +"/PR_curve.png")

Image.open(out_dir +"/confusion_matrix.png")

Image.open(out_dir +"/train_batch0.jpg")

# Load the best model we have so far:

model_file = out_dir + "/weights/best.pt"
model = YOLO(model_file)

# Load test image
image = cv2.imread("/content/drive/MyDrive/robotics_line/img_1.bmp")

# predict returns a list of Results object.
# Since we are running on a single image, we'll take the only one result
results = model.predict(image)[0]

results.names
print(results.to_json())
results.show()