int8 process_state -1 #     33013  State Indicator
int8 error_code -1 #        33014  Error Code
int8 error_state -1 #       13005  1 Error, 0 Ok 
int8 dice_detected_qa -1 #  13006  1 Die Detected, 0 Not Detected 
int8 dice_qa_pass -1 #      13007  1 QA Pass, 0 QA Fail
int8 dice_qa_replace -1 #   13008  1 Getting Dice Replacement, 0 No QA Action 
int8 hand_off_state -1 #    13009  1 Ready to Handoff, 0 Not Ready 


